development:
  # Trust in Lacuna Test PKI (for development purposes only!)
  trust_lacuna_test_root: true
  # THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

  # REST PKI parameters
  # -------------------
  rest_pki:
    # ======================================================
    #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
    # ======================================================
    access_token: 'uaWtaFA3BIioiduXVFGzcDfMqeZmr4bHppGeNuqQcycWY40tySeNzFxIBQzHvL9cnvV_-5q80BbkL2-ZsKTM3SfFmyNa7VHdhUx8l0fj7UiqpmtmPTJtmvSbhKt6nLX6edEcCSh8epA-IfMovaTkDzGeHtwOtZaJz2Yq2rlxmUTZBSHIadT0FhfuMvUD8ze5HFiEGrh34wkoBavrBbVPphSVwM2nQ11EupCYn_iWROpbFQPgCnqrZAmgTsIR7E48PKdy9BB645Fr_ZY1baojT3qoPBr6XDICea-GYx2emJmrmMCzJLi2iv3fbYdv0aVBCQdnkSFdsiNim5BHvix8RaHXXleNkintJqLVyhrCXGqC08GFA11XwctDvpzn-5ilVjb4ldBi6Fwinj3KepBv89hPsZZiDx7NULaA_se68wUB4_1k0Snde2WX1AuC_bZ3Ls3AYfgmgz_EYIiPG9AzKLhzmOMNapWoV5zroL2wEr7jxVzTD8CGWMxTgJltnoM6i6rONg'
    # This is a TRIAL token. It will expire at 31/03/2026. If the REST PKI
    # sample doesn't work, please contact our support by email:
    # suporte@lacunasoftware.com

    # In order to use this sample on a "on premises" installation of
    # REST PKI, fill the field below with the URL address of your REST PKI
    # installation (with the trailing '/' character).
    endpoint:

  # PKI Express parameters
  # ----------------------

  pki_express:
    # List of custom trusted roots. In this sample, we will get the certificate
    # files from private/ folder.
    trusted_roots: []

    # Offline mode. Set this, if you want that PKI Express to run on offline
    # mode. This mode is useful when there is no network available.
    offline: false

  # Web PKI parameters
  # ------------------

  web_pki:
    # Base64-encoded binary license for the Web PKI. This value is passed to
    # Web PKI component's constructor on JavaScript.
    license:

test:
  trust_lacuna_test_root: true

production:
  trust_lacuna_test_root: false
