development:
  # Trust in Lacuna Test PKI (for development purposes only!)
  trust_lacuna_test_root: true
  # THIS SHOULD NEVER BE USED ON A PRODUCTION ENVIRONMENT!

  # REST PKI parameters
  # -------------------
  rest_pki:
    # ======================================================
    #       >>>> PASTE YOUR REST PKI ACCESS TOKEN BELOW <<<<
    # ======================================================
    access_token: 'uT9CxxKrRFfCLvzjNwLIJZ6JCgbDs1982wYEFo87fHwC1_PwtaZIqkKvb4AWX_CAag1f-DJGn--oL8hSYy4ospgG5povjINEhS1wsdSAPhc8XqltzyYtdmNXhCfyFt7OzpKoqqMltKCR-R9i6VcMxl0GGPXTBB4X0hlqydI45fcV100N4eTcYCxd2O1u5GJ-bxiQdt75FTi6Wl2sjKKsG-qL3DjliF-uRDUuHIorLOEW774_am9lkNXEQz3gI9BWKxiv7bQOmOvVAUw3Y_Z6LLLdWx6aj3iU8xhVk2zWrD6AQNpREu07gFS4BvA0Ma2OuqJ438ClHtrTkV5BnCVTDD7ZyrUZSfSZLeCDg5fM9s-FWA-N-UIkg6eSjtyMUhgFN_YFU1-YX_Nd668foCjioU47WB_LL5FdbfpKSA3AYb8AYZGYxu3arKMMfoc2aq7I00G8glijwZXVVM5kC__K2vafnYrTwd8kksH4WxUd56uz9lFlANv2OqCYL2vID3xG2kARGg'
    # This is a TRIAL token. It will expire at 31/12/2025. If the REST PKI
    # sample doesn't work, please contact our support by email:
    # suporte@lacunasoftware.com

    # In order to use this sample on a "on premises" installation of
    # REST PKI, fill the field below with the URL address of your REST PKI
    # installation (with the trailing '/' character).
    endpoint:

  # PKI Express parameters
  # ----------------------

  pki_express:
    # List of custom trusted roots. In this sample, we will get the certificate
    # files from private/ folder.
    trusted_roots: []

    # Offline mode. Set this, if you want that PKI Express to run on offline
    # mode. This mode is useful when there is no network available.
    offline: false

  # Web PKI parameters
  # ------------------

  web_pki:
    # Base64-encoded binary license for the Web PKI. This value is passed to
    # Web PKI component's constructor on JavaScript.
    license:

test:
  trust_lacuna_test_root: true

production:
  trust_lacuna_test_root: false
